#!/bin/bash

# install PKG FOR VPN XL2TPD over IPSEC
sudo apt-get update && sudo apt-get install -y intltool libtool network-manager-dev libnm-util-dev libnm-glib-dev libnm-glib-vpn-dev libnm-gtk-dev libnm-dev libnma-dev ppp-dev libdbus-glib-1-dev libsecret-1-dev libgtk-3-dev libglib2.0-dev git strongswan libpcap0.8-dev
##################################################################################

##################################################################################
# install xl2tpd older version to kame work on ubuntu 16.04

cd /tmp
wget https://github.com/xelerance/xl2tpd/archive/v1.3.6/xl2tpd-1.3.6.tar.gz
tar xvzf xl2tpd-1.3.6.tar.gz
cd xl2tpd-1.3.6
make
sudo make install
##################################################################################
# install network manager script vor XL2TPD over IPSEC

cd /tmp
git clone https://github.com/nm-l2tp/network-manager-l2tp.git
cd network-manager-l2tp
./autogen.sh
./configure   --disable-static --prefix=/usr   --sysconfdir=/etc --libdir=/usr/lib/x86_64-linux-gnu   --libexecdir=/usr/lib/NetworkManager   --localstatedir=/var   --with-pppd-plugin-dir=/usr/lib/pppd/2.4.7

make
sudo make install
##################################################################################
# do not need this this is for ubuntu <16.04
#sudo ln -s /etc/apparmor.d/usr.lib.ipsec.charon /etc/apparmor.d/disable/
#sudo apparmor_parser -R /etc/apparmor.d/usr.lib.ipsec.charon
#sudo ln -s /etc/apparmor.d/usr.lib.ipsec.stroke /etc/apparmor.d/disable/
#sudo apparmor_parser -R /etc/apparmor.d/usr.lib.ipsec.stroke

##################################################################################
# Delete setup files
rm -rf ./xl2tpd-1.3.6.tar.gz ./xl2tpd-1.3.6 ./network-manager-l2tp
##################################################################################


echo 'Add VPN connection over network manager'
echo 'Do not touch anything else'
