#!/bin/sh

# File location
# /etc/ppp/ip-up
#       $1      the interface name used by pppd (e.g. ppp0)
#       $2      the tty device name
#       $3      the tty device speed
#       $4      the local IP address for the interface
#       $5      the remote IP address
#       $6      the parameter specified by the 'ipparam' option to pppd

#Permissions for the file
# chmod 755 


sudo /sbin/route add <subnet/ip/domain_name> -interface $1
sudo /sbin/route add <subnet/ip/domain_name> -interface $1
sudo /sbin/route add <subnet/ip/domain_name> -interface $1
sudo /sbin/route add <subnet/ip/domain_name> -interface $1
