#!/bin/sh

# File location
# /etc/ppp/ip-up

# Parameters which can be used in this script
# $1 The VPN interface
# $2  Unknown parameter
# $3 IP of the VPN server
# $4 VPN gateway address
# $5 Regular (non-vpn) gateway for LAN connections

#Permissions for the file
# chmod 755 


sudo /sbin/route add <subnet/ip/domain_name> -interface $1
sudo /sbin/route add <subnet/ip/domain_name> -interface $1
sudo /sbin/route add <subnet/ip/domain_name> -interface $1
sudo /sbin/route add <subnet/ip/domain_name> -interface $1
